name: Build & Deploy Container App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write    # for Azure OIDC
  contents: read

env:
  # === Customize these to your environment ===
  RESOURCE_GROUP: BEAM-N8N
  CONTAINER_APP_NAME: ingest-api
  ACR_NAME: beamn8nacr              # your ACR name (no domain)
  ACR_LOGIN_SERVER: beamn8nacr.azurecr.io
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: ingest-api
  FULL_IMAGE: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  TARGET_PORT: "8000"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI - Log in to ACR
        uses: azure/cli@v2
        with:
          inlineScript: |
            az acr login -n $ACR_NAME

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push image to ACR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.FULL_IMAGE }}

      # Option A: Deploy using official Container Apps deploy action
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.FULL_IMAGE }}
          # targetPort is only needed when creating a new app; harmless if set
          targetPort: ${{ env.TARGET_PORT }}

      # Option B (alternative): Deploy via Azure CLI
      # - name: Update image via Azure CLI
      #   uses: azure/cli@v2
      #   with:
      #     inlineScript: |
      #       az containerapp update \
      #         -g $RESOURCE_GROUP \
      #         -n $CONTAINER_APP_NAME \
      #         --image $FULL_IMAGE
